# Generated by Django 3.0 on 2021-10-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersmodel',
            name='acc_number',
            field=models.BigIntegerField(),
        ),
    ]
