# Generated by Django 3.0 on 2021-10-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20211022_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersmodel',
            name='acc_number',
            field=models.BigIntegerField(),
        ),
    ]
