# Generated by Django 3.0 on 2021-10-21 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('send_id', models.BigIntegerField(null=True)),
                ('recv_account', models.BigIntegerField(null=True)),
                ('trans_amt', models.BigIntegerField(null=True)),
                ('trans_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
