# Generated by Django 3.0 on 2021-10-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='send_id',
            new_name='send_account',
        ),
    ]
