# Generated by Django 3.0 on 2021-10-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211021_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='trans_date',
            new_name='trans_date_time',
        ),
    ]
