# Generated by Django 3.0 on 2021-10-26 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20211026_0627'),
        ('accounts', '0003_auto_20211021_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='recv_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recevier', to='customers.CustomersModel'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='send_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='customers.CustomersModel'),
        ),
    ]
