# Generated by Django 3.0 on 2021-10-10 00:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acc_number', models.BigIntegerField(max_length=15)),
                ('cust_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('ifsc_code', models.CharField(max_length=10)),
            ],
        ),
    ]
