# Generated by Django 3.0 on 2021-10-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20211010_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersmodel',
            name='total_amt',
            field=models.BigIntegerField(default=100),
        ),
    ]
