# Generated by Django 3.0 on 2021-10-22 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customersmodel_total_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersmodel',
            name='acc_number',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
